name: Update VPM Repository

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Run daily
  workflow_dispatch: # Allow manual trigger
  repository_dispatch:
    types: [update-repo] # Allow triggering from other repositories

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build index.json
        run: node build_repo.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
